%rebase templates/master

<h1>Documentation</h1>

<p>
    This website acts as a documention for the <a href="http://schema.org">Schema.org</a> external extension: <strong>netcomp</strong>.
</p>

<p>
    The structure and design of the documentation follow the one of Schema.org for more consistency with the core vocabulary. You will also find links to the core vocabulary everytime the extension use or extends one of their classes or properties.
</p>

<p>
    This extension includes <strong>{{ nbrClasses }}</strong> new classes, <strong>{{ nbrProperties }}</strong> new properties and <strong>{{ nbrPropertiesExtended }}</strong> extended properties.
</p>

<p>
    <em>
        Note that this documentation as well as the RDFA file have been auto-generated by a python script that you can find in the github repository. It might be useful if you are looking to create your own extension of Schema.org.
    </em>
</p>

<div id="thing_tree">
    <h3>netcomp extension without core vocabulary</h3>
    {{! hierarchyHtml }}
</div>